POST http://localhost:3001/api/login
Content-Type: application/json

{
        "laji": "Merikotka",
        "maara": "2",
        "kunta": "Joensuu",
        "paikka": "Kellotorni",
        "userId": "6081370ecbc9bcc926e78680",
        "lisatiedot": "Mitä se täällä tekee?"
}